#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SyringeTests.Resource", IsApplication=true)]

namespace SyringeTests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::SyringeTests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::SyringeTests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::SyringeTests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::SyringeTests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::SyringeTests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::SyringeTests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::SyringeTests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::SyringeTests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::SyringeTests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::SyringeTests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::SyringeTests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::SyringeTests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::SyringeTests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::SyringeTests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::SyringeTests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::SyringeTests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::SyringeTests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::SyringeTests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::SyringeTests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::SyringeTests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::SyringeTests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::SyringeTests.Resource.Layout.test_suite;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int AnimationResource = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int AnimatorResource = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0c0000
			public const int IntegerArrayResource = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int StringArrayResource = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int TypedArrayResource = 2131492866;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int BooleanResource = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int ColorResource = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ColorStateListResource = 2131230721;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int DimensionResource = 2131296256;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0003
			public const int OptionHostName = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int OptionPort = 2131558404;
			
			// aapt resource value: 0x7f0d0002
			public const int OptionRemoteServer = 2131558402;
			
			// aapt resource value: 0x7f0d0014
			public const int OptionsButton = 2131558420;
			
			// aapt resource value: 0x7f0d000f
			public const int ResultFullName = 2131558415;
			
			// aapt resource value: 0x7f0d0011
			public const int ResultMessage = 2131558417;
			
			// aapt resource value: 0x7f0d0010
			public const int ResultResultState = 2131558416;
			
			// aapt resource value: 0x7f0d000e
			public const int ResultRunSingleMethodTest = 2131558414;
			
			// aapt resource value: 0x7f0d0012
			public const int ResultStackTrace = 2131558418;
			
			// aapt resource value: 0x7f0d0008
			public const int ResultsFailed = 2131558408;
			
			// aapt resource value: 0x7f0d0005
			public const int ResultsId = 2131558405;
			
			// aapt resource value: 0x7f0d0009
			public const int ResultsIgnored = 2131558409;
			
			// aapt resource value: 0x7f0d000a
			public const int ResultsInconclusive = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int ResultsMessage = 2131558411;
			
			// aapt resource value: 0x7f0d0007
			public const int ResultsPassed = 2131558407;
			
			// aapt resource value: 0x7f0d0006
			public const int ResultsResult = 2131558406;
			
			// aapt resource value: 0x7f0d0013
			public const int RunTestsButton = 2131558419;
			
			// aapt resource value: 0x7f0d0015
			public const int TestSuiteListView = 2131558421;
			
			// aapt resource value: 0x7f0d0000
			public const int javaCastNativeToolbar = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int javaCastSupportToolbar = 2131558401;
			
			// aapt resource value: 0x7f0d000c
			public const int simpleButton = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public const int simpleCheckBox = 2131558413;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int IntegerResource = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int JavaCastRequiredLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int options = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int results = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SimpleLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_result = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_suite = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0001
			public const int ApplicationName = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int StringResource = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f060000
			public const int XmlResource = 2131099648;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
